import LocalizedStrings from 'react-native-localization';
export let FCMToken = ""
export let strings = new LocalizedStrings({
  dk: {
    Next: 'Næste',
    Title: 'Når det ER tanken der tæller',
    Text: 'Med stiicky kan du nu give en personlig videohilsen via det fysiske gavemærke.',
    Title2: 'Personlig og sjov pengegave',
    Text2: 'Tilføj en pengegave sammen  med din personlige hilsen.',
    Title3: 'Overraskende og meget glædelig',
    Text3: 'Sæt stiicky gavemærket på din gave, uket blomster eller lignende og se modtagerens reaktion over den helt unikke og personlige gave.',
    Login: 'Er du allerede oprettet? Log in',
    LoginTitle: 'Fordi alle fortjerner en personlig gave',
    LoginText: 'Og en gave uden en stiicky, aldrig vil være det samme igen.',
    PhoneNumberInputText: 'Brug dit telefonnummer til at oprette bruger eller log på stiicky.',
    PhoneNumberInputTitle: 'Indtast mobilnummer.',
    UserNameText: 'Vi anbefaler, at du skriver dit fulde navn,da det automatisk vil blive brugt som afsender på dine personlige hilser. ',
    Logo: 'stiicky',
    Fillinlater: 'Udfyld senere',
    createUserScreenTitle: 'Fordi alle fortjerner en personlig gave',
    createUserScreenText: 'Og en gave uden en stiicky, aldrig vil være det samme igen..',
    Login: 'Log In',
    alreadyCreatedTitle: 'Er du allerede oprettet?',
    CreateUserButton: 'Opret bruger',
    ProgressBarTitle: 'create an account',
    PhoneInputTopText: 'Brug dit telefonnummer til at oprette bruger eller log på',
    PhoneInputTopText2: 'stiicky.',
    PhoneInputTitle: 'Type mobile number',
    // PhoneInputBottomText:'Use your phone number to create user or log in to',
    // PhoneInputBottomText2: 'stiicky.',
    phoneInputButton: ' Videre',
    OtpTitle: 'Type SMS code',
    OtpText: 'En verifikationskode er sendt til:',
    OtpText2: ' +45 31 18 00 19',
    usernameText: 'Vi anbefaler, at du skriver dit fulde navn, da det automatisk vil blive brugt som afsender på dine personlige hilser. ',
    usernameTitle: 'Type your name',
    useremailTitle: 'Type your email',
    useremailText: 'This information is used to approve and manage your profile.',
    HomeTabottomText: 'HAPPY DINOTOPIA BIRTHDAY',
    HomeTabbottomText2: 'Pris: 0 kr. ',
    GiveButton: 'Give',
    RedeemButton: 'Redeem',
    HomeTabText: 'more festive, when the recipient redeems and opens it!',
    HomeTabTitle: 'Populair',
    EnterVerifiCationcode: 'Enter verification code',
    SendNewCode: 'Send New Code',
    Fillinlater: 'Udfyld senere',
    DistinationButton: 'Continue without name',
    DestinationToptext: 'Tilføj/rediger modtager og afsender.',
    DestinationTitle: 'To',
    DestinationTitle2: 'From',
    AddMoneyScreenProgressBarTitle: 'Pengegave',
    AddMoneyScreenText: 'Tilføj og giv en pengegave med din',
    AddMoneyScreenText2: ' eller fortsæt uden.',
    AddMoneyScreenButtonText: 'Continue without',
    OtpModelButton: 'Back',
    OtpModelButton2: 'Continue',
    OtpModelText: 'Dit telefonnummer:',
    OtpModelText2: ' er allerede oprettet på denne app.',
    OtpModelText3: 'Ønsker du at logge på?',
    UserCardsProgresbarTitle: 'Oversigt',
    UserCardsText1: 'Indpakning valgt',
    UserCardsText2: 'Fødselsdag',
    UserCardsText3: 'Pengegave tilføjet',
    UserCardsText4: '300 kr.',
    UserCardsText5: 'Skriv her for at tilføje en ekstra lille hilsen…',
    Continue: 'Continue',
    WritingScreenTitleTop: 'Hilsen',
    WritingScreenText: 'Skriv en lille ekstra hilsen.',
    Activation: "Activation",
    PhoneInputBottomText: 'Jeg har læst og accepteret:',
    PhoneInputBottomText2: 'Betingelserne  ',
    PhoneInputBottomText3: 'for at bruge',
    EmailText: "Denne information bliver brugt til at godkende og administrere din profil.",
    AddMoneyValue: "Add money value",
    DeselectVoucher: "Deselect voucher",
    Kr: "Kr.",
    buyOverview: 'køb oversigt:',
    PaymentActivateText1: 'Vær klar med din',
    PaymentActivateText2: 'gavemærke, som du snart bliver nødt til at opbevare',
    DeselectVoucher: "Fravælg voucher",
    PaymentScreenText1: "1 x Indpakning Fødselsdag	0,00 kr.",
    PaymentScreenText2: "1 x Standard video hilsen	0,00 kr.",
    PaymentScreenText3: "1 x Pengegave	",
    PaymentScreenText4: "1 x Aktiveringsgebyr xx,xx kr.",
    PaymentScreenText5: "I alt	",
    PaymentScreenText6: "Heraf moms xx,xx kr.",
    PaymentScreenText7: "Jeg har læst og accepteret:",
    PaymentScreenText8: " Købsbetingelserne",
    PaymentScreenText9: "at købe en ",
    PaymentScreenPayWith: 'Pay with',
    PaymentScreenMobilePay: 'MobilePay',
    Pay: "Pay",
    Profile: "Profil",
    Name: "Navn",
    MobileNumber: "Mobilnummer",
    MobileNumber2: "+45 31 18 00 19",
    Email: 'Email',
    Email2: 'mathiasmønsted@gmail.com',
    PaymentProfiel: "Payment cards & accounts",
    About: "Om",
    ProfileConditions: 'Vilkår og Betingelser',
    ProfilePrivacy: "Fortrolighedspolitik",
    logout: 'Log ud',
    birthday: "birthday",
    Save: "Gem",
    EditMailTitle: "Skift e-mail",
    EditMailText: "Disse oplysninger bruges til at godkende og administrere din profil",
    EditMailInputTitle: "indtast din e-mail",
    EditMobileNumberTitle: "Skift mobilnummer",
    EditMobileNumberText: "Du modtager en bekræftelseskode via SMS.",
    EditMobileNumberText2: "Indtast telefonnummer",
    ChangeNameEditName: "Ændre navn",
    ChangeNameEditNameText: "Vi anbefaler, at du skriver dit fulde navn, da det automatisk bruges som afsender på dine personlige hilsner.",
    EditOtpButton: "Gem nyt telefonnummer",
    EditOtpTitle: "Indtast verifikationskode",
    HomeCardText: 'ælg indpakning og gør din',
    ActivationScrTitle: 'Mærket er aktiveret',
    ActivationScrText: 'OVERRASKENDE',
    ActivationScrText2: 'lige hvad du vil give.',
    ActivationScrText3: 'PERSONLIG',
    ActivationScrText4: 'Du leverer din gave og introducerer din',
    ActivationScrText5: 'ØNSKET',
    ActivationScrText5: 'Modtageren scanner din',
    ActivationScrText6: 'og glæd dig igen og igen og ...',
    StickerScreenText: "Når du bestiller din egen",
    StickerScreenText2: "Denne voucher giver dig:",
    viaMobilePay: 'via MobilePay',
    Gotoshop: "Gå til butik",
    Gifttags: 'gave tags.',
    receipt: "kvittering",
    PaymentScreenText: 'Der er foretaget en pengegavebetaling til:',
    PaymentShowScreenTopText: "Betal kontant gave",
    PaymentShowScreenText: "Indtast dit telefonnummer, du bruger til MobilePay.",
    PaymentShowScreenButtonText: "Gem i tegnebog",
    PaymentScreenShowButoon: 'Betal ud via',
    PaymentScreenShowButoonText: 'Tilbage til oversigt',
    bottomText: 'Some text here',
    PreviewText: "Se hvordan det ser ud, når modtageren indløser sin Stiicky.",
    PaymentCompletedTitle: "Gennemført",
    PaymentCompletedText: "Betaling gennemført",
    ActivatebtnText: "Aktiver",
    PaymentGift: "Udbetaling af pengegaver",
    Mobilenumbertext: "Du vil få pengegaver udbetalt via dette telefonnummer:",
    PaymentMethod: "Betalingsmetoder",
    open: "Åben",
    CountdownText1: " Husk lyd på din telefon!",
    CountdownText2: "Er du klar…",
    RedeemVouncherText: "Indløs voucher",
    SaveandClose: "Gem & luk",
    RedeemPaymentText1: "Indtast dit telefonnummer du bruger til MobilePay. ",
    CashGift: "Udbetal pengegave",
    PurchaseOverview:"Købsoverblik",
    BackToOverView:"Tilbage til oversigt",
    OverViewText1:"Der er blevet fortaget en pengegave udbetaling til:",
    AmountPaidOut:" Beløb udbetalt",
    Edit :"Rediger",
    update :"Opdatering",
    ContinueWithoutMoney : "Continue without money",
    ToFrom:"Til & Fra",
    ContinueWithoutToname:"continue without ToName",
    chooseone:"Vælg en",
    Videos: "Videoer",
    Images :"Images",
    ContinueWithoutImageVideo: "continue without Image/Video",
    VouncherAdded:'Voucher tilføjet',
    VoucherScreenText: "Vælg en valgfri gratis voucher du kan give med som en lille ekstra gave og overraskelse.",
    Voucher :"Voucher",
    info : "Info",
    ChooseWrapingText:"Vælg indpakning og lav din",
    notification:"Notifikation",
    ReadytoScan:"Klar to scanning",
    TapNFC:"Tryk venligst på NFC -tags",
    SendNotifications:"Lad os sende dig notifikationer for at sikre, at du ikke går glip af nogen opdatering",
    TurnOnNotification:"Tænd venligst beskeden",
    neverMissNotification:"På denne måde går du aldrig glip af det",
    LatestUpdates:"seneste opdateringer.",
    NotNow:"Ikke nu",
    OK :"Okay",
    start :"start",
    cancel:"afbestille",
    MobilePay:" MobilePay",
    OpenCamera:"Åbent kamera",
    ChooseFromGallary:"Vælg mellem Gallary",
    SendNewOtp :"Send New Otp",
    flashTip :"Blitz on/off"




  },
  en: {
    Next: 'Next',
    Title: 'When it is the thought that counts',
    Text: 'With stiicky you can now give a personal video greeting via the physical gift tag.',
    Title2: 'Personal and fun pengegave',
    Text2: 'Add a monetary gift together with your personal greeting.',
    Title3: 'Surprising and very joyful',
    Text3: 'Put the stiicky gift tag on your gift, a bouquet of flowers or the like and see the recipient reaction to the completely unique and personal gift.',
    Login: 'Are you already created? Log in',
    LoginTitle: 'Because everyone deserves a personal gift',
    LoginText: 'And a gift without a stiicky, will never be the same again.',
    PhoneNumberInputTitle: 'Type mobile number.',
    PhoneNumberInputText: 'Use your phone number to create user or log in to stiicky.',
    UserNameText: 'We recommend that you write your full name,as it will automatically be used as sender on your personal greetings.',
    Logo: 'stiicky',
    createUserScreenTitle: ' Because everyone deserves a personal gift',
    createUserScreenText: 'And a gift without a',
    createUserScreenText2: ' will never be the same again.',
    stiicky: ' stiicky,',
    Login: 'Log In',
    alreadyCreatedTitle: 'Are you already created?',
    CreateUserButton: 'CREATE AN ACCOUNT',
    ProgressBarTitle: 'Create User',
    PhoneInputTopText: 'Use your phone number to create user or log in to',
    PhoneInputTopText2: 'stiicky.',
    PhoneInputTitle: 'Type mobile number',
    PhoneInputBottomText: 'I have read and accepted:',
    PhoneInputBottomText2: 'The conditions ',
    PhoneInputBottomText3: 'for using',
    phoneInputButton: ' Continue',
    OtpTitle: 'Type SMS code',
    OtpText: 'A verification code has been sent to:',
    OtpText2: ' +45 31 18 00 19',
    usernameText: 'We recommend that you type your full name, as it will automatically be used as a sender on your personal greetings.',
    usernameTitle: 'Type your name',
    useremailTitle: 'Type your email',
    useremailText: 'This information is used to approve and manage your profile.',
    HomeTabbottomText: 'HAPPY DINOTOPIA BIRTHDAY ',
    HomeTabbottomText2: 'Pris: 0 kr. ',
    GiveButton: 'Give',
    RedeemButton: 'Redeem',
    HomeTabText: 'more festive, when the recipient redeems and opens it!',
    HomeTabTitle: 'Popular',
    EnterVerifiCationcode: 'Enter verification code',
    SendNewCode: 'Send New Code',
    DistinationButton: 'Continue without name',
    Fillinlater: 'Fill in later',
    DestinationButton: 'Continue without name',
    DestinationToptext: 'Add / edit recipient and sender.',
    DestinationTitle: 'To',
    DestinationTitle2: 'From',
    AddMoneyScreenProgressBarTitle: 'Money gift',
    AddMoneyScreenText: 'Add and give a monetary gift with your',
    AddMoneyScreenText2: ' or continue without.',
    AddMoneyScreenButtonText: 'Continue without',
    AddMoneyScreenButtonText2: 'Gem',
    OtpModelButton: 'Back',
    OtpModelButton2: 'Continue',
    OtpModelText: 'Your phone number:',
    OtpModelText2: 'is already created on this app.',
    OtpModelText3: 'Do you want to log in?',
    UserCardsProgresbarTitle: 'Overview',
    UserCardsText1: 'Wrapping selected',
    UserCardsText2: 'Birthday',
    UserCardsText3: 'Cash gift added',
    UserCardsText4: '300 kr.',
    UserCardsText5: 'Write here to add an extra little greeting…',
    WritingScreenTitleTop: 'Regards',
    WritingScreenText: 'Write a little extra greeting.',
    Activation: "Activation",
    EmailText: "This information is used to approve and manage your profile.",
    AddMoneyValue: "Add money value",
    Kr: "Kr.",
    PaymentActivateText1: 'Be ready with your ',
    PaymentActivateText2: 'gift tag which you will soon have to keep',
    DeselectVoucher: "Deselect voucher",
    buyOverview: 'buy overview:',
    PaymentScreenText1: "1 x Wrapping Birthday DKK 0.00.",
    PaymentScreenText2: "1 x Standard video greeting DKK 0.00.",
    PaymentScreenText3: "1 x Money gift ",
    PaymentScreenText4: "1 x Activation fee ",
    PaymentScreenText5: "Total ",
    PaymentScreenText6: "Of which VAT xx, xx kr.",
    PaymentScreenText7: " I have read and accepted:",
    PaymentScreenText8: " The terms of purchase",
    PaymentScreenText9: " to buy one ",
    PaymentScreenPayWith: 'Pay with',
    PaymentScreenMobilePay: 'MobilePay',
    Pay: "Pay",
    Profile: "Profile",
    Name: "Name",
    MobileNumber: "MobileNumber",
    MobileNumber2: "+45 31 18 00 19",
    Email: 'Email',
    Email2: 'mathiasmønsted@gmail.com',
    PaymentProfiel: "Payment cards & accounts",
    About: "About",
    ProfileConditions: 'Terms & Conditions',
    ProfilePrivacy: "Privacy Policy",
    logout: 'Log out',
    wrappingSelected: "wrapping selected",
    birthday: "birthday",
    Save: "Save",
    Continue: 'Continue',
    HomeTabottomText: 'HAPPY DINOTOPIA BIRTHDAY',
    EditMailTitle: "Change email",
    EditMailText: "This information is used to approve and manage your profile",
    EditMailInputTitle: "enter your e-mail",
    EditMobileNumberTitle: "Change mobile number",
    EditMobileNumberText: "You will receive a verification code via SMS.",
    EditMobileNumberText2: "Enter phone number",
    ChangeNameEditName: "Change name",
    ChangeNameEditNameText: "We recommend that you write your full name, as it will automatically be used as sender on your personal greetings.",
    EditOtpButton: "Save new phone number",
    EditOtpTitle: "Enter verification code",
    HomeCardText: "Choose wrapping and make your",
    ActivationScrTitle: 'The mark is activated',
    ActivationScrText: 'SURPRISING',
    ActivationScrText2: 'just what you want to give.',
    ActivationScrText3: 'PERSONAL',
    ActivationScrText4: 'You deliver your gift, and introduce your',
    ActivationScrText5: 'DESIRED',
    ActivationScrText5: 'The receiver scans your',
    ActivationScrText6: 'and rejoice again and again and…',
    PaymentShowScreenTopText: "Pay out cash gift",
    PaymentShowScreenText: "Type your phonenumber you use for MobilePay.",
    PaymentShowScreenButtonText: "Save to wallet",
    PaymentScreenShowButoon: 'Pay out via ',
    PaymentScreenShowButoonText: 'Back to overview',
    PaymentScreenText: 'A monetary gift payment has been made to:',
    receipt: "receipt",
    viaMobilePay: 'via MobilePay',
    Gotoshop: "Go to shop",
    Gifttags: ' gift tags.',
    StickerScreenText: " When ordering your own",
    StickerScreenText2: "This voucher gives you:",
    FREEDELIVERY: "FREE DELIVERY",
    bottomText: 'Some text here',
    PreviewText: "See what it looks like, reaches the recipient redeems his Stiicky.",
    PaymentCompletedTitle: "Completed",
    PaymentCompletedText: "Payment completed",
    ActivatebtnText: "Activate",
    PaymentGift: "Payment of monetary gifts",
    Mobilenumbertext: "You will receive cash gifts via this phone number:",
    PaymentMethod: "Payment methods",
    open: "Open",
    CountdownText1: "Remember sound your phone!",
    CountdownText2: "Are you ready?",
    RedeemVouncherText: "Redeem voucher",
    SaveandClose: "Save & close",
    RedeemPaymentText1: "Enter your phone number you use for MobilePay.",
    CashGift:"Payout cash gift",
    PurchaseOverview:"Purchase overview",
    BackToOverView:"Back to overview",
    OverViewText1:"A monetary gift payment has been made to:",
    AmountPaidOut:"Amount paid out",
    Edit :"Edit",
    update : "Update",
    ContinueWithoutMoney:"Continue without money",
    ToFrom :"To & From",
    ContinueWithoutToname:"continue without ToName",
    chooseone :"Choose one",
    Videos:"Videos",
    Images :"Images",
    ContinueWithoutImageVideo: "continue without Image/Video",
    VouncherAdded:"Voucher added",
    VoucherScreenText:"Choose an optional free voucher you can give with as a little extra gift and surprise.",
    Voucher :"Voucher",
    info : "Info",
    ChooseWrapingText:"Choose wrapping and make your",
    notification:"Notification",
    ReadytoScan:"Ready to scan",
    TapNFC:"Please tap NFC tags",
    SendNotifications : "Let us send you notifications to make sure you dont miss any update",
    TurnOnNotification : "Please Turn On Notification",
    neverMissNotification :"This way, you will never miss out",
    LatestUpdates:"latest updates",
    NotNow :"Not now",
    OK:"OK",
    start:"start",
    cancel:"Cancel",
    MobilePay:" MobilePay",
    OpenCamera:"Open Camera",
    ChooseFromGallary:"Choose from Gallary",
    SendNewOtp :"Send New Otp",
    flashTip:"Flash on/off"

    







  },
});
